### makes sure that postgresql is installed.
--- # tells that the document will me YML.
- hosts: all # Tells which hosts this playbook applies too.
  become: yes # tell the playbook to use sudo.
  tasks: #The things that will be runned.
  - name: Ensure postgresql is installed. # this and the yum: checks to see if the RPM is installed and if not installs it.
    yum: name=postgresql-server state=present #make sure the "name" is the correct package name. Ansible will not know the difference.
  - name: Ensure postgresql is running. # this last two parts make sure that the service is started and running
service: name=postgresql-server state=started enabled=yes
