---

- hosts: all
  become: yes
  
  tasks:
  - name: Install all the needed packages
    yum: name={{ item }} state=present
    with_items:
       - ntpd
       - nagios
       - ccze
  command: yum update -y
