---

- hosts: all

 tasks:
  - name: Install Apache.
   command: yum install --quiet httpd httpd-devel mod_ssl -y
   - name: copy configuration files.
     command: > # > tells ansible the next few lines and one long string
      cp httpd.conf /etc/httpd/conf/httpd.conf
  - command: >
      cp httpd-vhosts.conf /etc/httpd/conf/httpd-vhosts.conf
  - name: start Apache and run in boot
    command: service httpd start
    command: chkconfig httpd on
    
